

name: CI
on:
  ## Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  #trigger on pull request for staging and trying
  pull_request:
      branches:
      - staging
      - trying
  #on push on staging and trying
  push:
    branches:
      - staging
      - trying

#All jobs that will run for this workflow.
jobs:
#For now all tests do NOt run in parallel. They all run sequentially in one job.
#In the future we can use docker-save docker-restore and the action cache,
#to create parallel jobs. Cache (https://github.com/actions/cache) can be used 
#to share the build images between all jobs :)
  tests:
    name: tests
    runs-on: ubuntu-latest
    #depends on the clamav db file being updated
    steps:
      - uses: actions/checkout@v2
      - name: check docker-compose version
        run: docker-compose -v
      - name: login docker
        env:
          DOCKER_UN: ${{ secrets.Docker_Login }}
          DOCKER_PW: ${{ secrets.Docker_Password }}
        run: echo "$DOCKER_PW" | docker login --username $DOCKER_UN --password-stdin
      - name: build all docker images
        env:
          MAILU_VERSION: ${{ env.GITHUB_REF }}
          TRAVIS_BRANCH: ${{ env.GITHUB_REF }}
        run: docker-compose -f tests/build.yml build
      - name: copy all certs
        run: sudo -- sh -c 'mkdir -p /mailu && cp -r tests/certs /mailu && chmod 600 /mailu/certs/*'      
      - name: test core suite
        run: python tests/compose/test.py core 1
        env:
          MAILU_VERSION: ${{ env.GITHUB_REF }}
          TRAVIS_BRANCH: ${{ env.GITHUB_REF }}        
      - name: test fetch
        run: python tests/compose/test.py fetchmail 1
        env:
          MAILU_VERSION: ${{ env.GITHUB_REF }}
          TRAVIS_BRANCH: ${{ env.GITHUB_REF }}        
      #very important step that caches the mailu database files!
      - name: 'Cache clamav DB'
        uses: actions/cache@v2
        with:
          path: /mailu/filter/
          key: clamav-db
      - name: 'test clamvav'
        run: python tests/compose/test.py filters 10
        env:
          MAILU_VERSION: ${{ env.GITHUB_REF }}
          TRAVIS_BRANCH: ${{ env.GITHUB_REF }} 
      - name: test rainloop
        run: python tests/compose/test.py rainloop 1
        env:
          MAILU_VERSION: ${{ env.GITHUB_REF }}
          TRAVIS_BRANCH: ${{ env.GITHUB_REF }}        
      - name: test roundcube
        run: python tests/compose/test.py roundcube 1
        env:
          MAILU_VERSION: ${{ env.GITHUB_REF }}
          TRAVIS_BRANCH: ${{ env.GITHUB_REF }}        
      - name: test webdav
        run: python tests/compose/test.py webdav 1
        env:
          MAILU_VERSION: ${{ env.GITHUB_REF }}
          TRAVIS_BRANCH: ${{ env.GITHUB_REF }}        

#Must be changed in the future. With travis, the deploy script shared the build context.
#now we rebuild all images what takes time. We must investigate if we can somehow share 
#the build context between job tests and job deploy. 
#Perhaps we could make use of caching. The limit is 5GB for the cache
#https://github.com/actions/cache
  deploy:
    name: deploy
    needs:
      - tests
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: check docker-compose version
        run: docker-compose -v
      - name: login docker
        env:
          DOCKER_UN: ${{ secrets.Docker_Login }}
          DOCKER_PW: ${{ secrets.Docker_Password }}
        run: echo "$DOCKER_PW" | docker login --username $DOCKER_UN --password-stdin
      - name: build all docker images
        run: docker-compose -f tests/build.yml build
        env:
          MAILU_VERSION: ${{ env.GITHUB_REF }}
          TRAVIS_BRANCH: ${{ env.GITHUB_REF }}        
      - name: deploy build docker images
        env:
          DOCKER_UN: ${{ secrets.Docker_Login }}
          DOCKER_PW: ${{ secrets.Docker_Password }}
          MAILU_VERSION: ${{ env.GITHUB_REF }}
          TRAVIS_BRANCH: ${{ env.GITHUB_REF }}          
        run: bash tests/deploy.sh

 # This job should depend on all required jobs.
 # We will make Bors watch this job to tell whether to merge or not.
  ci-success:
    name: CI-Done
    #Returns true when none of the **previous** steps have failed or been canceled.
    if: ${{ success() }}
    needs: 
      - tests
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded.
        run: exit 0


