

name: CI
on:
  ## Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  #trigger on pull request for staging and trying
#  pull_request:
#      branches:
#      - staging
#      - trying
  #on push on staging and trying
  push:
    branches:
      - staging
      - testing
      - '1.5'
      - '1.6'
      - '1.7'
      - '1.8'
      - master
      # version tags, e.g. 1.7.1
      - '[1-9].[0-9].[0-9]'
      # pre-releases, e.g. 1.8-pre1
      - 1.8-pre[0-9]
    # test branches, e.g. test-debian
      - test-*

#All jobs that will run for this workflow.
jobs:
#For now all tests do NOt run in parallel. They all run sequentially in one job.
#In the future we can use docker-save docker-restore and the action cache,
#to create parallel jobs. Cache (https://github.com/actions/cache) can be used 
#to share the build images between all jobs :)


  tests:
    name: build and test
    runs-on: ubuntu-latest
    #depends on the clamav db file being updated
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: |
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: install python packages
        run: python3 -m pip install -r tests/requirements.txt
      - name: check docker-compose version
        run: docker-compose -v
      - name: login docker
        env:
          DOCKER_UN: ${{ secrets.Docker_Login }}
          DOCKER_PW: ${{ secrets.Docker_Password }}
          DOCKER_ORG: ${{ secrets.DOCKER_ORG }}
        run: echo "$DOCKER_PW" | docker login --username $DOCKER_UN --password-stdin
      - name: create folder for storing/caching images
        run: mkdir images     
      - name: Cache docker images
        uses: actions/cache@v2
        with:
          path: images/images.tar.gz
          key: docker-images-${{ env.BRANCH }}-${{ github.sha }}-${{ github.run_id }}
      - name: pull docker images for building
      
      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
       # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: build all docker images
        env:
          MAILU_VERSION: ${{ env.BRANCH }}
          TRAVIS_BRANCH: ${{ env.BRANCH }}
          DOCKER_ORG: ${{ secrets.DOCKER_ORG }}
        run: docker-compose -f tests/build.yml build
      - name: save all docker images for reusage
        env:
          DOCKER_ORG: ${{ secrets.DOCKER_ORG }}
        run: docker save $DOCKER_ORG/admin $DOCKER_ORG/clamav $DOCKER_ORG/docs $DOCKER_ORG/dovecot $DOCKER_ORG/fetchmail $DOCKER_ORG/nginx $DOCKER_ORG/none $DOCKER_ORG/postfix $DOCKER_ORG/postgresql $DOCKER_ORG/radicale $DOCKER_ORG/rainloop $DOCKER_ORG/roundcube $DOCKER_ORG/rspamd $DOCKER_ORG/setup $DOCKER_ORG/traefik-certdumper $DOCKER_ORG/unbound -o images/images.tar.gz 
      - name: copy all certs
        run: sudo -- sh -c 'mkdir -p /mailu && cp -r tests/certs /mailu && chmod 600 /mailu/certs/*'      
      - name: test core suite
        run: python tests/compose/test.py core 1
        env:
          MAILU_VERSION: ${{ env.BRANCH }}
          TRAVIS_BRANCH: ${{ env.BRANCH }} 
          DOCKER_ORG: ${{ secrets.DOCKER_ORG }}
      - name: test fetch
        run: python tests/compose/test.py fetchmail 1
        env:
          MAILU_VERSION: ${{ env.BRANCH }}
          TRAVIS_BRANCH: ${{ env.BRANCH }}
          DOCKER_ORG: ${{ secrets.DOCKER_ORG }}
      #very important step that caches the mailu database files!
      - name: 'Cache clamav DB'
        uses: actions/cache@v2
        with:
          path: /mailu/filter/main.cvd
          key: clamav-db
      - name: 'test clamvav'
        run: python tests/compose/test.py filters 2
        env:
          MAILU_VERSION: ${{ env.BRANCH }}
          TRAVIS_BRANCH: ${{ env.BRANCH }} 
          DOCKER_ORG: ${{ secrets.DOCKER_ORG }}
      - name: test rainloop
        run: python tests/compose/test.py rainloop 1
        env:
          MAILU_VERSION: ${{ env.BRANCH }}
          TRAVIS_BRANCH: ${{ env.BRANCH }} 
          DOCKER_ORG: ${{ secrets.DOCKER_ORG }}
      - name: test roundcube
        run: python tests/compose/test.py roundcube 1
        env:
          MAILU_VERSION: ${{ env.BRANCH }}
          TRAVIS_BRANCH: ${{ env.BRANCH }} 
          DOCKER_ORG: ${{ secrets.DOCKER_ORG }}
      - name: test webdav
        run: python tests/compose/test.py webdav 1
        env:
          MAILU_VERSION: ${{ env.BRANCH }}
          TRAVIS_BRANCH: ${{ env.BRANCH }}
          DOCKER_ORG: ${{ secrets.DOCKER_ORG }}

#Uses https://github.com/actions/cache. Using artefacts is not an option due to the 500MB limit.
#The tar.gz file with all images is ~2GB. So using actions/cache is our only option.
#actions/cache has a 5GB limit. It uses a FIFO policy. Once 5GB is reached the first stored item
#is deleted from the cache.
  deploy:
    name: deploy
    needs:
      - tests
    runs-on: ubuntu-latest
    env:
      DOCKER_ORG: diman0
    steps: 
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: |
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: check docker-compose version
        run: docker-compose -v
      - name: login docker
        env:
          DOCKER_UN: ${{ secrets.Docker_Login }}
          DOCKER_PW: ${{ secrets.Docker_Password }}
        run: echo "$DOCKER_PW" | docker login --username $DOCKER_UN --password-stdin
      - name: create folder for storing/caching images
        run: mkdir images
      - name: Cache docker images
        id: cache
        uses: actions/cache@v2
        with:
          path: images/images.tar.gz
          key: docker-images-${{ env.BRANCH }}-${{ github.sha }}-${{ github.run_id }}
      - name: Load docker images
        if: steps.cache.outputs.cache-hit == 'true'
        run: docker load -i images/images.tar.gz
      - uses: satackey/action-docker-layer-caching@v0.0.11
        if: steps.cache.outputs.cache-hit != 'true'
       # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true        
      - name: build all docker images
        if: steps.cache.outputs.cache-hit != 'true'
        run: docker-compose -f tests/build.yml build
        env:
          MAILU_VERSION: ${{ env.BRANCH }}
          TRAVIS_BRANCH: ${{ env.BRANCH }}
          DOCKER_ORG: ${{ secrets.DOCKER_ORG }}
      - name: deploy build docker images
        env:
          DOCKER_UN: ${{ secrets.Docker_Login }}
          DOCKER_PW: ${{ secrets.Docker_Password }}
          DOCKER_ORG: ${{ secrets.DOCKER_ORG }}
          MAILU_VERSION: ${{ env.BRANCH }}
          TRAVIS_BRANCH: ${{ env.BRANCH }}
          TRAVIS_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: bash tests/deploy.sh

 # This job should depend on all required jobs.
 # We will make Bors watch this job to tell whether to merge or not.
  ci-success:
    name: CI-Done
    #Returns true when none of the **previous** steps have failed or been canceled.
    if: ${{ success() }}
    needs: 
      - tests
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded.
        run: exit 0


